name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/img/**"
      - "docs/api/**"
      - "docs/site-docs.zip"
      - "datasets/snapshots/**"
  push:
    branches: [main]
    paths-ignore:
      - "docs/img/**"
      - "docs/api/**"
      - "docs/site-docs.zip"
      - "datasets/snapshots/**"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  baseline:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ghtriage
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure main exists for Turbo filter
        run: git fetch origin main:refs/remotes/origin/main --depth=1 || true

      - name: Setup Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Repo layout check
        run: pnpm repo:layout:check

      - name: Lint
        run: pnpm lint

      - name: Prebuild schemas (fix TS2307 workspace resolution)
        run: pnpm -F @ghtriage/schemas build

      - name: Typecheck
        run: pnpm typecheck

      - name: Build changed graph
        run: pnpm build
      - name: Prepare database schema
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ghtriage
        run: |
          psql "$DATABASE_URL" -f infra/sql/002_ghapp.sql || true
          psql "$DATABASE_URL" -c '\dt'
      - name: KPI Schema + Validation
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ghtriage
          GITHUB_WEBHOOK_SECRET: testsecret
        run: pnpm vitest run --config vitest.ci.config.ts

      - name: Tests (fast) with coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ghtriage
          GITHUB_WEBHOOK_SECRET: testsecret
        run: pnpm ci:test

      - name: Coverage summary (markdown)
        run: node tooling/ci/coverage-summary.mjs >> $GITHUB_STEP_SUMMARY || true
