name: CI (baseline)

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/img/**"
      - "docs/api/**"
      - "docs/site-docs.zip"
      - "datasets/snapshots/**"
      - ".github/workflows/**" # specialized workflows handle themselves
  push:
    branches: [main]
    paths-ignore:
      - "docs/img/**"
      - "docs/api/**"
      - "docs/site-docs.zip"
      - "datasets/snapshots/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  baseline:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure main exists for Turbo filter
        run: git fetch origin main:refs/remotes/origin/main --depth=1 || true

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Install dependencies (frozen on main)
        run: pnpm install ${{ github.ref == 'refs/heads/main' && '--frozen-lockfile' || '--no-frozen-lockfile' }}

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Prebuild schemas (fix TS2307 workspace resolution)
        run: pnpm -F @ghtriage/schemas build

      - name: Build changed graph
        run: pnpm build

      - name: Tests (fast) with coverage
        run: pnpm ci:test

      - name: Coverage summary (markdown)
        run: node tooling/ci/coverage-summary.mjs >> $GITHUB_STEP_SUMMARY || true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: |
            coverage
            **/coverage
          if-no-files-found: ignore
