name: Contracts

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - uses: actions/checkout@v4

      # First: Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Second: Enable Corepack and activate pnpm explicitly
      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          echo "pnpm version:"
          pnpm -v

      # Third: Enable pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build schemas and contracts
      - name: Build schemas and contracts
        run: |
          pnpm -F @ghtriage/schemas build
          pnpm -F @ghtriage/contracts build

      # Generate OpenAPI + JSON Schema
      - name: Generate OpenAPI + JSON Schema
        run: |
          pnpm contracts:openapi
          pnpm contracts:jsonschema

      # Lint OpenAPI
      - name: Lint OpenAPI (Redocly)
        run: pnpm contracts:lint

      # Run tests
      - name: Run contract/unit tests
        run: pnpm test:contracts

      # Upload artifacts
      - name: Upload contract artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts-artifacts
          path: |
            docs/openapi/*.json
            docs/jsonschema/*.json
          if-no-files-found: error
