name: Docs

on:
  push:
    branches: [main]
    # Do not run if the ONLY change is the lockfile
    paths-ignore:
      - "pnpm-lock.yaml"
  # allow manual runs if needed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20 (cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies (incl. devDeps)
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Build API docs (OpenAPI + TypeDoc)
        run: pnpm docs:api

      - name: Zip site docs
        run: pnpm docs:zip

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-docs
          path: |
            docs/site-docs.zip
            docs/api
          if-no-files-found: error
