name: Docs

on:
  push:
    branches: [ main ]
    # Skip if the ONLY change is the lockfile
    paths-ignore:
      - 'pnpm-lock.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack and activate pnpm from package.json
        run: |
          corepack enable
          # Enforce the exact version in package.json: "packageManager": "pnpm@9.12.0"
          corepack prepare pnpm@$(jq -r '.packageManager | split("@")[1]' package.json) --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Build API docs (OpenAPI + TypeDoc)
        run: pnpm docs:api

      - name: Zip site docs
        run: pnpm docs:zip

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-docs
          path: |
            docs/site-docs.zip
            docs/api
          if-no-files-found: error
