name: Docs

on:
  push:
    branches: [main]
    # Skip if the ONLY change is the lockfile
    paths-ignore:
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      - name: Install dependencies (incl. devDeps)
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - name: Build workspace (tsc)
        run: pnpm -r --filter @ghtriage/schemas --filter @ghtriage/kpi-spec --if-present run build

      - name: Build API docs (OpenAPI + TypeDoc)
        run: pnpm docs:api

      - name: Zip site docs
        run: pnpm docs:zip

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-docs
          path: |
            docs/site-docs.zip
            docs/api
          if-no-files-found: error
