name: Docs
on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "docs/openapi/**"
      - "typedoc.json"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # needed for uploading artifacts
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Generate OpenAPI & TypeDoc & Redoc
        run: pnpm docs:api

      # Optional: JSON Schema -> HTML (human-friendly)
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install json-schema-for-humans
        run: pip install json-schema-for-humans
      - name: Render JSON Schema docs
        run: |
          mkdir -p docs/api/jsonschema
          for f in docs/jsonschema/*.schema.json; do
            [ -f "$f" ] || continue
            out="docs/api/jsonschema/$(basename "${f%.schema.json}").html"
            generate-schema-doc --link-to-schema --expand-buttons --minify --config show_breadcrumbs=true "$f" "$out"
          done

      - name: Zip site
        run: pnpm docs:zip

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-docs
          path: docs/site-docs.zip
          if-no-files-found: warn
