name: GH App (P2.1)

on:
    pull_request:
        branches: [main]
        paths:
            - "apps/bff/src/github/**"
            - "apps/bff/test/**"
            - "packages/contracts/src/github.ts"
            - "infra/sql/002_ghapp.sql"
            - ".github/workflows/ghapp.yml"
    push:
        branches: [main]
        paths:
            - "apps/bff/src/github/**"
            - "apps/bff/test/**"
            - "packages/contracts/src/github.ts"
            - "infra/sql/002_ghapp.sql"
            - ".github/workflows/ghapp.yml"

permissions: { contents: read }

jobs:
    ghapp:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: { node-version: 20.19.0 }
            - uses: pnpm/action-setup@v4
              with: { version: 9.12.0, run_install: false }
            - run: pnpm install --frozen-lockfile
            - name: Build packages
              run: |
                  pnpm -F @ghtriage/schemas build || true
                  pnpm -F @ghtriage/contracts build || true
                  pnpm -F @ghtriage/bff build || true
            - name: Unit tests (BFF GHAPP)
              run: pnpm -F @ghtriage/bff vitest run --coverage
