name: KPI Spec

on:
  pull_request:
    branches: [main]
    paths:
      - "docs/kpis.yaml"
      - "packages/schemas/kpis.schema.json"
      - "tooling/validate-kpis.ts"
      - ".github/workflows/kpi-lint.yml"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/ghtriage
      GITHUB_WEBHOOK_SECRET: testsecret
    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ghtriage
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      # Enable Corepack BEFORE setup-node when using cache: pnpm
      - name: Enable pnpm (Corepack)
        run: corepack enable && corepack prepare pnpm@9.12.0 --activate

      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Build core schemas dependencies
        run: |
          pnpm -w --filter @ghtriage/schemas build
          pnpm -w --filter @ghtriage/contracts build
          pnpm -w --filter @ghtriage/kpi-spec build
          pnpm -w --filter @ghtriage/cli build

      - name: Build CLI
        run: |
          pnpm -w --filter @ghtriage/kpi-spec build
          pnpm -w --filter @ghtriage/cli build

      - name: Validate KPIs (CLI)
        run: pnpm kpi:check

      - name: Unit tests (KPIs)
        run: pnpm test:kpi

      - name: Render KPI table
        run: node tooling/print-kpis.mjs

      - uses: actions/upload-artifact@v4
        with:
          name: kpi-schema-and-spec
          path: |
            packages/schemas/kpis.schema.json
            docs/kpis.yaml
            docs/kpis.md
