name: KPI Spec

on:
  pull_request:
    branches: [main]
    paths:
      - "docs/kpis.yaml"
      - "packages/kpi-spec/**"
      - "scripts/kpi_*"
      - ".github/workflows/kpi-lint.yml"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  validate:
    # Only run if the CLI exists in this branch
    if: ${{ exists('packages/cli/package.json') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "pnpm" }

      - name: Enable pnpm (Corepack)
        run: corepack enable && corepack prepare pnpm@9.12.0 --activate

      - run: pnpm i --frozen-lockfile
      - run: pnpm run schema:kpi
      - run: pnpm run kpi:check

      - uses: actions/upload-artifact@v4
        with:
          name: kpi-schema-and-spec
          path: |
            packages/schemas/kpis.schema.json
            docs/kpis.yaml

      - name: Skip note
        if: steps.has_cli.outputs.present != 'true'
        run: echo "KPI CLI not present yet; skipping KPI checks for this repo state."
