name: KPI Spec
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - docs/kpis.yaml
      - packages/kpi-spec/**
      - packages/cli/**
      - package.json

jobs:
  kpi:
    if: ${{ exists('packages/cli/package.json') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20.19.0", cache: "pnpm" }

      - name: Enable pnpm (Corepack)
        run: corepack enable && corepack prepare pnpm@9.12.0 --activate

      - run: pnpm -w i

      - run: pnpm --filter @ghtriage/kpi-spec run build
      - run: pnpm --filter @ghtriage/cli run build
      - run: pnpm --filter @ghtriage/cli run kpi:schema
      - run: pnpm --filter @ghtriage/cli run kpi:check
