name: Security

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deps-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node, no built-in cache here
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      #  Explicitly enable Corepack + pnpm
      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      # (optional but recommended) cache pnpm store
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run dependency audit
        run: pnpm audit --audit-level=high || true
