name: Security & Compliance Scan

on:
  pull_request:
    paths:
      - "datasets/**"
      - "scripts/**"
      - "packages/shared/**"
      - "docs/security_policy.md"

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run redaction scan (PII validator)
        run: pnpm security:redact

      - name: Run Trivy (dependency vulnerability scan)
        uses: aquasecurity/trivy-action@0.16.1
        with:
          scan-type: fs
          severity: CRITICAL,HIGH

      - name: Run Gitleaks (secret detection)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --no-git --redact --source . --config=.gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run security unit & integration tests
        run: pnpm test:security
