name: Security
on:
  pull_request:
  push:
    branches: [main]

jobs:
  deps-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "pnpm" }
      - run: corepack enable && corepack prepare pnpm@9.12.0 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit --audit-level=high || true
