name: Security

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1" # weekly on Mondays
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # CodeQL scan
  codeql:
    name: CodeQL (JS/TS)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - uses: github/codeql-action/autobuild@v3

      - name: Analyze & upload CodeQL results
        uses: github/codeql-action/analyze@v3
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}

  # SBOM generator
  sbom:
    name: SBOM (SPDX)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom-${{ github.sha }}.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom-*.spdx.json

  # Trivy dependency scanner
  trivy-fs:
    name: Dependency scan (Trivy)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: aquasecurity/trivy-action@0.21.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy.sarif
          trivy-config: |
            {
              "skipUpdate": true,
              "timeout": "10m",
              "cacheDir": "/tmp/trivy-cache"
            }

      # Only upload to Code Scanning if authorized
      - name: Upload SARIF to code scanning
        if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'mht-ashkezari' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      # Otherwise keep artifact for review
      - name: Upload SARIF as artifact (fork PRs)
        if: ${{ github.event_name == 'pull_request' || github.repository_owner != 'mht-ashkezari' }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-sarif
          path: trivy.sarif

  # Advisory audit
  deps-audit:
    name: pnpm audit (advisory)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run dependency audit (non-blocking)
        run: pnpm audit --audit-level=high || true
