# .github/workflows/selacc-tests.yml
name: SELACC Tests
on:
  pull_request:
    branches: [main]
    paths:
      - "tests/selacc*.spec.ts"
      - "apps/bff/src/**"
      - "docs/access/**"
      - "docs/selection/**"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch: {}

jobs:
  selacc-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Enable Corepack BEFORE setup-node when using cache: pnpm
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack prepare pnpm@9.12.0 --activate
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:selacc

  selacc-e2e:
    runs-on: ubuntu-latest
    env:
      SELACC_APP_MODULE_PATH: apps/bff/src/app.module
      GITHUB_WEBHOOK_SECRET: testsecret
    steps:
      - uses: actions/checkout@v4
      # Enable Corepack BEFORE setup-node when using cache: pnpm
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack prepare pnpm@9.12.0 --activate
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:selacc:e2e
